# Project information
site_name: API Testing Material
site_url: https://github.com/fabianpg95/apiTesting-material

# Repository
repo_name: apiTesting-material
repo_url: https://github.com/fabianpg95/apiTesting-material

# Page tree
nav:
    - Fundamentals:
      - 'Introduction': 'Fundamentals/introduction.md'
      - 'Portocols API': 'Fundamentals/history.md'
      - 'REST': 'Fundamentals/rest.md'
      - 'HTTP methods': 'Fundamentals/http-methods.md' 
      - 'Status Codes': 'Fundamentals/status-codes.md' 
      - 'API Tester - considerations': 'Fundamentals/api-test-cons.md' 

    - Postman:
      - 'Collections & Env vars': 'Postman/collect-envvars.md'
      - 'Headers': 'Postman/headers.md' 
      - 'Body': 'Postman/body.md' 
      - 'Authorization': 'Postman/authorization.md'
      - 'Test Scripts': 'Postman/test-scripts.md' 
      - 'Tokens': 'Postman/tokens.md' 
      - 'cURL': 'Postman/curl.md'
      - 'Monitors': 'Postman/monitors.md' 
      - 'Newman CLI': 'Postman/newman.md' 
      - 'API Doc': 'Postman/api-doc.md' 
  
    - Authn & Authz:
      - 'Authn vs Authz': 'Auth-Authz/authn-authz.md'
      - Authn:
       # - 'Authn Intro': 'Auth-Authz/Authn/authn.md'
        - 'Authn Methods': 'Auth-Authz/Authn/authn-methods.md'
      #  - 'Authn considerations': 'Authn/authn-consid.md'
      - Authz:
       # - 'Authz Intro': 'Auth-Authz/Authz/authz.md'
        - 'Authz Methods': 'Auth-Authz/Authz/authz-methods.md'
      #  - 'Authz considerations': 'Authn/authz-consid.md'
      - 'SAML': 'Auth-Authz/saml.md'
      - 'CORS': 'Auth-Authz/cors.md'

    #- Swagger:
    #  - 'Swagger': 'API-Docum/swagger.md'

    - API Tools:
      - 'API Tools': 'API-Tools/types.md'

    - Tips & Best Practices:
      #- 'Intro': 'Tips-Best-Practices/intro.md'
      - 'Best practices': 'Tips-Best-Practices/best-prac.md'

# Configurations
theme:
  name: "material"
  language: "en"

  # Configuration
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: "Roboto"
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - header.autohide
    - toc.autohide
    - content.code.annotate
  extra:
    version:
      method: mike

# Plugins
plugins:
  - search
  - git-revision-date

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

